// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Button = require("@material-ui/core/Button/Button");
var IconButton = require("@material-ui/core/IconButton/IconButton");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -459040882,
    "extendedFab"
  ],
  /* tuple */[
    5094087,
    "fab"
  ],
  /* tuple */[
    613841570,
    "outlined"
  ],
  /* tuple */[
    1064531251,
    "contained"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -499495052,
    "secondary"
  ],
  /* tuple */[
    58474434,
    "primary"
  ]
];

function colorToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray$1);
}

function colorFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray$1, param);
}

function make(variant, onClick, color, children) {
  var tmp = {
    onClick: onClick
  };
  var tmp$1 = Js_option.map(variantToJs, variant);
  if (tmp$1 !== undefined) {
    tmp.variant = Caml_option.valFromOption(tmp$1);
  }
  var tmp$2 = Js_option.map(colorToJs, color);
  if (tmp$2 !== undefined) {
    tmp.color = Caml_option.valFromOption(tmp$2);
  }
  return ReasonReact.wrapJsForReason(Button.default, tmp, children);
}

function make$1(onClick, className, children) {
  var tmp = {
    onClick: onClick
  };
  var tmp$1 = Js_option.map((function (a) {
          return a;
        }), className);
  if (tmp$1 !== undefined) {
    tmp.className = Caml_option.valFromOption(tmp$1);
  }
  return ReasonReact.wrapJsForReason(IconButton.default, tmp, children);
}

var IconButton$1 = /* module */[/* make */make$1];

exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.colorToJs = colorToJs;
exports.colorFromJs = colorFromJs;
exports.make = make;
exports.IconButton = IconButton$1;
/* ReasonReact Not a pure module */
