// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ArrowBackRounded = require("@material-ui/icons/ArrowBackRounded");
var ArrowForwardRounded = require("@material-ui/icons/ArrowForwardRounded");

function make(className, children) {
  return ReasonReact.wrapJsForReason(ArrowForwardRounded.default, {
              className: Js_null_undefined.fromOption(className)
            }, children);
}

var Forward = /* module */[/* make */make];

function make$1(className, children) {
  return ReasonReact.wrapJsForReason(ArrowBackRounded.default, {
              className: Js_null_undefined.fromOption(className)
            }, children);
}

var Back = /* module */[/* make */make$1];

exports.Forward = Forward;
exports.Back = Back;
/* ReasonReact Not a pure module */
