// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var TextField = require("@material-ui/core/TextField/TextField");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -361220291,
    "standard"
  ],
  /* tuple */[
    86969762,
    "filled"
  ],
  /* tuple */[
    613841570,
    "outlined"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -271659236,
    "email"
  ],
  /* tuple */[
    561678025,
    "number"
  ]
];

function type_ToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function type_FromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

function make(value, fullWidth, onChange, label, type_, $staropt$star, disabled, children) {
  var variant = $staropt$star !== undefined ? $staropt$star : /* standard */-361220291;
  return ReasonReact.wrapJsForReason(TextField.default, {
              variant: variantToJs(variant),
              type: type_ToJs(type_),
              value: value,
              label: label,
              fullWidth: fullWidth,
              onChange: onChange,
              disabled: Js_null_undefined.fromOption(disabled)
            }, children);
}

exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.type_ToJs = type_ToJs;
exports.type_FromJs = type_FromJs;
exports.make = make;
/* ReasonReact Not a pure module */
