// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var root = Css.style(/* :: */[
      Css.height(/* `percent */[
            -119887163,
            100.0
          ]),
      /* :: */[
        Css.width(/* `percent */[
              -119887163,
              100.0
            ]),
        /* :: */[
          Css.position(/* absolute */-1013592457),
          /* :: */[
            Css.backgroundImage(Css.linearGradient(Css.grad(0.0), /* :: */[
                      /* tuple */[
                        0,
                        /* `hex */[
                          5194459,
                          "A5A6C5"
                        ]
                      ],
                      /* :: */[
                        /* tuple */[
                          100,
                          /* `hex */[
                            5194459,
                            "F8DFC9"
                          ]
                        ],
                        /* [] */0
                      ]
                    ])),
            /* [] */0
          ]
        ]
      ]
    ]);

var innerRoot = Css.style(/* :: */[
      Css.padding(Css.px(16)),
      /* :: */[
        Css.position(Css.absolute),
        /* :: */[
          Css.top(/* `percent */[
                -119887163,
                50.0
              ]),
          /* :: */[
            Css.left(/* `percent */[
                  -119887163,
                  50.0
                ]),
            /* :: */[
              Css.transform(Css.translate(/* `percent */[
                        -119887163,
                        -50.0
                      ], /* `percent */[
                        -119887163,
                        -50.0
                      ])),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* root */root,
  /* innerRoot */innerRoot
];

exports.Styles = Styles;
/* root Not a pure module */
