// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Button = require("@material-ui/core/Button/Button");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -459040882,
    "extendedFab"
  ],
  /* tuple */[
    5094087,
    "fab"
  ],
  /* tuple */[
    613841570,
    "outlined"
  ],
  /* tuple */[
    1064531251,
    "contained"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

function make(variant, onClick, children) {
  var tmp = {
    onClick: onClick
  };
  var tmp$1 = Js_option.map(variantToJs, variant);
  if (tmp$1 !== undefined) {
    tmp.variant = Caml_option.valFromOption(tmp$1);
  }
  return ReasonReact.wrapJsForReason(Button.default, tmp, children);
}

exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.make = make;
/* ReasonReact Not a pure module */
