// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Grid = require("@material-ui/core/Grid/Grid");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -485895757,
    "space-around"
  ],
  /* tuple */[
    -162316795,
    "stretch"
  ],
  /* tuple */[
    98248149,
    "center"
  ],
  /* tuple */[
    516682146,
    "space-between"
  ],
  /* tuple */[
    662439529,
    "flex-start"
  ],
  /* tuple */[
    924268066,
    "flex-end"
  ]
];

function alignContentToJs(param) {
  return Js_mapperRt.binarySearch(6, param, jsMapperConstantArray);
}

function alignContentFromJs(param) {
  return Js_mapperRt.revSearch(6, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -162316795,
    "stretch"
  ],
  /* tuple */[
    98248149,
    "center"
  ],
  /* tuple */[
    287825029,
    "baseline"
  ],
  /* tuple */[
    662439529,
    "flex-start"
  ],
  /* tuple */[
    924268066,
    "flex-end"
  ]
];

function alignItemsToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray$1);
}

function alignItemsFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray$1, param);
}

var jsMapperConstantArray$2 = /* array */[
  /* tuple */[
    -963948842,
    "column"
  ],
  /* tuple */[
    5693978,
    "row"
  ],
  /* tuple */[
    135477484,
    "column-reverse"
  ],
  /* tuple */[
    378951208,
    "row-reverse"
  ]
];

function directionToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray$2);
}

function directionFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray$2, param);
}

var jsMapperConstantArray$3 = /* array */[
  /* tuple */[
    -1016061555,
    "space-evenly"
  ],
  /* tuple */[
    -485895757,
    "space-around"
  ],
  /* tuple */[
    98248149,
    "center"
  ],
  /* tuple */[
    516682146,
    "space-between"
  ],
  /* tuple */[
    662439529,
    "flex-start"
  ],
  /* tuple */[
    924268066,
    "flex-end"
  ]
];

function justifyToJs(param) {
  return Js_mapperRt.binarySearch(6, param, jsMapperConstantArray$3);
}

function justifyFromJs(param) {
  return Js_mapperRt.revSearch(6, jsMapperConstantArray$3, param);
}

var jsMapperConstantArray$4 = /* array */[
  0,
  8,
  16,
  32
];

function spacingToJs(param) {
  return Js_mapperRt.toInt(param, jsMapperConstantArray$4);
}

function spacingFromJs(param) {
  return Js_mapperRt.fromInt(4, jsMapperConstantArray$4, param);
}

function make($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, children) {
  var alignContent = $staropt$star !== undefined ? $staropt$star : /* flexStart */662439529;
  var alignItems = $staropt$star$1 !== undefined ? $staropt$star$1 : /* flexStart */662439529;
  var direction = $staropt$star$2 !== undefined ? $staropt$star$2 : /* row */5693978;
  var justify = $staropt$star$3 !== undefined ? $staropt$star$3 : /* flexStart */662439529;
  var spacing = $staropt$star$4 !== undefined ? $staropt$star$4 : /* Zero */0;
  return ReasonReact.wrapJsForReason(Grid.default, {
              alignContent: alignContentToJs(alignContent),
              alignItems: alignItemsToJs(alignItems),
              direction: directionToJs(direction),
              justify: justifyToJs(justify),
              spacing: spacingToJs(spacing),
              container: true
            }, children);
}

function make$1(ml, children) {
  return ReasonReact.wrapJsForReason(Grid.default, {
              ml: Js_null_undefined.fromOption(ml)
            }, children);
}

var Item = /* module */[/* make */make$1];

exports.alignContentToJs = alignContentToJs;
exports.alignContentFromJs = alignContentFromJs;
exports.alignItemsToJs = alignItemsToJs;
exports.alignItemsFromJs = alignItemsFromJs;
exports.directionToJs = directionToJs;
exports.directionFromJs = directionFromJs;
exports.justifyToJs = justifyToJs;
exports.justifyFromJs = justifyFromJs;
exports.spacingToJs = spacingToJs;
exports.spacingFromJs = spacingFromJs;
exports.make = make;
exports.Item = Item;
/* ReasonReact Not a pure module */
