// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Grid$KnitZilla = require("./mat-bindings/Grid.bs.js");
var Button$KnitZilla = require("./mat-bindings/button.bs.js");
var Typography$KnitZilla = require("./mat-bindings/Typography.bs.js");

function initialState(param) {
  return /* record */[/* rows */0];
}

function reducer(action, state) {
  if (action) {
    return /* Update */Block.__(0, [/* record */[/* rows */0]]);
  } else {
    return /* Update */Block.__(0, [/* record */[/* rows */state[/* rows */0] + 1 | 0]]);
  }
}

var component = ReasonReact.reducerComponent("RowCalculator");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Grid$KnitZilla.make(undefined, /* center */98248149, /* column */-963948842, undefined, undefined, /* array */[
                              ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Typography$KnitZilla.make(/* h6 */23246, undefined, undefined, /* array */[String(self[/* state */1][/* rows */0])]))])),
                              ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Grid$KnitZilla.make(undefined, undefined, undefined, undefined, undefined, /* array */[
                                                  ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Button$KnitZilla.make(/* text */-856044371, (function (_e) {
                                                                        return Curry._1(self[/* send */3], /* Increment */0);
                                                                      }), undefined, /* array */["+1"]))])),
                                                  ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Button$KnitZilla.make(/* text */-856044371, (function (_e) {
                                                                        return Curry._1(self[/* send */3], /* Reset */1);
                                                                      }), undefined, /* array */["Reset"]))]))
                                                ]))]))
                            ]));
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component;
exports.make = make;
/* component Not a pure module */
