// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$KnitZilla = require("./App.bs.js");
var Grid$KnitZilla = require("./mat-bindings/Grid.bs.js");
var Button$KnitZilla = require("./mat-bindings/button.bs.js");
var Typography$KnitZilla = require("./mat-bindings/Typography.bs.js");
var NavigationIcons$KnitZilla = require("./mat-bindings/NavigationIcons.bs.js");

var floatingRightSideBack = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.top(/* `percent */[
              -119887163,
              50.0
            ]),
        /* :: */[
          Css.left(Css.px(5)),
          /* [] */0
        ]
      ]
    ]);

var numberWrapper = Css.style(/* :: */[
      Css.border(Css.px(1), Css.solid, Css.rgba(0, 0, 0, 0.87)),
      /* :: */[
        Css.borderRadius(Css.px(5)),
        /* :: */[
          Css.padding2(Css.px(12), Css.px(24)),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* floatingRightSideBack */floatingRightSideBack,
  /* numberWrapper */numberWrapper
];

function initialState(param) {
  return /* record */[/* rows */0];
}

function reducer(action, state) {
  if (action) {
    return /* Update */Block.__(0, [/* record */[/* rows */0]]);
  } else {
    return /* Update */Block.__(0, [/* record */[/* rows */state[/* rows */0] + 1 | 0]]);
  }
}

var component = ReasonReact.reducerComponent("RowCalculator");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement(React.Fragment, undefined, React.createElement("div", {
                              className: App$KnitZilla.Styles[/* innerRoot */0]
                            }, ReasonReact.element(undefined, undefined, Grid$KnitZilla.make(undefined, /* center */98248149, /* column */-963948842, undefined, undefined, /* array */[
                                      ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[React.createElement("div", {
                                                      className: numberWrapper
                                                    }, ReasonReact.element(undefined, undefined, Typography$KnitZilla.make(/* h6 */23246, undefined, undefined, /* array */[String(self[/* state */1][/* rows */0])])))])),
                                      ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Grid$KnitZilla.make(undefined, undefined, undefined, undefined, undefined, /* array */[
                                                          ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Button$KnitZilla.make(/* text */-856044371, (function (_e) {
                                                                                return Curry._1(self[/* send */3], /* Increment */0);
                                                                              }), undefined, /* array */["+1"]))])),
                                                          ReasonReact.element(undefined, undefined, Grid$KnitZilla.Item[/* make */0](undefined, /* array */[ReasonReact.element(undefined, undefined, Button$KnitZilla.make(/* text */-856044371, (function (_e) {
                                                                                return Curry._1(self[/* send */3], /* Reset */1);
                                                                              }), undefined, /* array */["Reset"]))]))
                                                        ]))]))
                                    ]))), React.createElement("div", {
                              className: floatingRightSideBack,
                              onClick: (function (_e) {
                                  return ReasonReact.Router[/* push */0]("/");
                                })
                            }, ReasonReact.element(undefined, undefined, NavigationIcons$KnitZilla.Back[/* make */0](undefined, /* array */[]))));
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component;
exports.make = make;
/* floatingRightSideBack Not a pure module */
