// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var $$Touch = /* module */[];

var $$Touch$1 = /* module */[/* Touch */$$Touch];

exports.$$Touch = $$Touch$1;
/* No side effect */
